"""add_uploaded_files_table_v2

Revision ID: c0061eef6642
Revises: 5a3d3b91af86
Create Date: 2025-12-08 11:25:14.725864

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0061eef6642"
down_revision: Union[str, None] = "5a3d3b91af86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("folder", sa.String(length=100), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_index(
        op.f("ix_uploaded_files_filename"),
        "uploaded_files",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_files_folder"),
        "uploaded_files",
        ["folder"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_files_id"),
        "uploaded_files",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploaded_files_id"), table_name="uploaded_files")
    op.drop_index(op.f("ix_uploaded_files_folder"), table_name="uploaded_files")
    op.drop_index(op.f("ix_uploaded_files_filename"), table_name="uploaded_files")
    op.drop_table("uploaded_files")
    # ### end Alembic commands ###
